export const HSS_ERROR = {
  PATH_OUTSIDE_CWD: "PATH_OUTSIDE_CWD",
  UNSUPPORTED_ARTIFACT: "UNSUPPORTED_ARTIFACT",
  ARTIFACT_NOT_FOUND: "ARTIFACT_NOT_FOUND",
  MAP_NOT_FOUND: "MAP_NOT_FOUND",
  SYMBOL_NOT_FOUND: "SYMBOL_NOT_FOUND",
  SYMBOL_UNSAFE: "SYMBOL_UNSAFE",
  SYMBOL_DUPLICATE: "SYMBOL_DUPLICATE",
  SYMBOL_NOT_RAM: "SYMBOL_NOT_RAM",
  SYMBOL_KIND_UNSUPPORTED: "SYMBOL_KIND_UNSUPPORTED",
  SYMBOL_ARRAY_LAYOUT_UNKNOWN: "SYMBOL_ARRAY_LAYOUT_UNKNOWN",
  SYMBOL_ARRAY_LENGTH_UNKNOWN: "SYMBOL_ARRAY_LENGTH_UNKNOWN",
  SYMBOL_ARRAY_SIZE_MISMATCH: "SYMBOL_ARRAY_SIZE_MISMATCH",
  SYMBOL_POINTER_NOT_ALLOWED: "SYMBOL_POINTER_NOT_ALLOWED",
  SYMBOL_DYNAMIC_ARRAY_NOT_ALLOWED: "SYMBOL_DYNAMIC_ARRAY_NOT_ALLOWED",
  SYMBOL_INCOMPLETE_ARRAY_NOT_ALLOWED: "SYMBOL_INCOMPLETE_ARRAY_NOT_ALLOWED",
  HSS_DLL_MISSING: "HSS_DLL_MISSING",
  HSS_DLL_EXPORTS_MISSING: "HSS_DLL_EXPORTS_MISSING",
  HSS_HELPER_MISSING: "HSS_HELPER_MISSING",
  HSS_HELPER_TIMEOUT: "HSS_HELPER_TIMEOUT",
  HSS_HELPER_BAD_JSON: "HSS_HELPER_BAD_JSON",
  HSS_TARGET_HALTED: "HSS_TARGET_HALTED",
  HSS_CAPTURE_ACTIVE: "HSS_CAPTURE_ACTIVE",
  HSS_CAPTURE_NOT_FOUND: "HSS_CAPTURE_NOT_FOUND",
  HSS_CAPTURE_NOT_TERMINAL: "HSS_CAPTURE_NOT_TERMINAL",
  HSS_CRC_MISMATCH: "HSS_CRC_MISMATCH",
  HSS_CAPABILITY_LIMIT: "HSS_CAPABILITY_LIMIT",
  HSS_EXPORT_EXISTS: "HSS_EXPORT_EXISTS",
  POLICY_NOT_FOUND: "POLICY_NOT_FOUND",
  POLICY_INVALID_JSON: "POLICY_INVALID_JSON",
  POLICY_UNSUPPORTED_VERSION: "POLICY_UNSUPPORTED_VERSION",
  POLICY_TARGET_NOT_ALLOWLISTED: "POLICY_TARGET_NOT_ALLOWLISTED",
  POLICY_TYPE_MISMATCH: "POLICY_TYPE_MISMATCH",
  POLICY_VALUE_OUT_OF_RANGE: "POLICY_VALUE_OUT_OF_RANGE",
  POLICY_VALUE_NOT_ALLOWED: "POLICY_VALUE_NOT_ALLOWED",
  POLICY_MAX_WRITES_EXCEEDED: "POLICY_MAX_WRITES_EXCEEDED",
  POLICY_MAX_ELEMENTS_EXCEEDED: "POLICY_MAX_ELEMENTS_EXCEEDED",
  POLICY_ARRAY_INDEX_NOT_ALLOWED: "POLICY_ARRAY_INDEX_NOT_ALLOWED",
  POLICY_ARRAY_SLICE_NOT_ALLOWED: "POLICY_ARRAY_SLICE_NOT_ALLOWED",
  POLICY_ARRAY_INDEX_OUT_OF_RANGE: "POLICY_ARRAY_INDEX_OUT_OF_RANGE",
  POLICY_ARRAY_SLICE_OUT_OF_RANGE: "POLICY_ARRAY_SLICE_OUT_OF_RANGE",
  POLICY_MAX_BYTES_EXCEEDED: "POLICY_MAX_BYTES_EXCEEDED",
  POLICY_RISK_NOT_EXECUTABLE: "POLICY_RISK_NOT_EXECUTABLE",
  POLICY_CAPTURE_TIME_WRITE_DISABLED: "POLICY_CAPTURE_TIME_WRITE_DISABLED",
} as const;

export type HssErrorCode = typeof HSS_ERROR[keyof typeof HSS_ERROR];

export class HssError extends Error {
  constructor(
    readonly code: HssErrorCode,
    message: string,
    readonly details: Record<string, unknown> = {},
  ) {
    super(message);
  }
}

export function hssError(error: unknown): HssError {
  if (error instanceof HssError) return error;
  return new HssError("HSS_HELPER_BAD_JSON", error instanceof Error ? error.message : String(error));
}
